branch-defaults:
  main:
    environment: HanMartket-env
environment-defaults:
  martket:
    branch: null
    repository: null
global:
  application_name: hanmartket
  default_ec2_keyname: hanmartket
  default_platform: "PHP 8.4 running on 64bit Amazon Linux 2023"
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: hanmartket
  workspace_type: Application
