location ~ /\.(env|git|svn|hg|htaccess|DS_Store) {
    deny all;
}

location ~* \.(composer\.(json|lock)|package\.json|yarn\.lock|phpunit\.xml|sql|tar|gz|zip|bak)$ {
    deny all;
}

location ~ ^/(vendor|node_modules|tests)/ {
    deny all;
}

location ~ \.\./ {
    deny all;
}

location ~* (phpunit|eval-stdin|thinkphp|pearcmd|docker) {
    deny all;
}

error_page 404 403 409      /404.html;
error_page 500 502 503 504  /50x.html;

location = /404.html {
    root /var/www/html/public;
}

location = /50x.html {
    root /var/www/html/public;
}

# block CRLF injection (%0A, %0D)
if ($request_uri ~* "%0A|%0D") { return 400; }

# block SSRF attempts to access internal IPs
set $block 0;
if ($query_string ~* "(localhost|127\.0\.0\.1|0\.0\.0\.0|::1|169\.254\.169\.254|10\.[0-9\.]+|192\.168\.[0-9\.]+|172\.(1[6-9]|2[0-9]|3[0-1])\.[0-9\.]+)") { set $block 1; }
if ($request_uri ~* "(localhost|127\.0\.0\.1|169\.254\.169\.254|10\.[0-9\.]+|192\.168\.[0-9\.]+|172\.(1[6-9]|2[0-9]|3[0-1])\.[0-9\.]+)") { set $block 1; }
if ($http_host ~* "(localhost|127\.0\.0\.1|169\.254\.169\.254|10\.[0-9\.]+|192\.168\.[0-9\.]+|172\.(1[6-9]|2[0-9]|3[0-1])\.[0-9\.]+)") { set $block 1; }
if ($block = 1) { return 403; }

# Basic SQL Injection and XSS prevention
set $malicious 0;
if ($query_string ~* "(union\s+select|(\%27)|(')|(\-\-)|(\%23)|(#)|(\;)|<script|(\%3C)|>|etc/passwd|boot\.ini|(http|https|ftp|ftps|php):\/\/|(\`|\$\(.*\)))") { set $malicious 1; }
if ($malicious = 1) { return 403; }
