# Application-specific nginx snippets for Elastic Beanstalk
# Place any location blocks needed by the app here.

location ~* \.\(js|css|woff2?|ttf|svg|eot|png|jpg|jpeg|gif|ico\)$ {
    add_header Content-Security-Policy "default-src 'none'; style-src 'self'; script-src 'self'; font-src 'self'; img-src 'self';" always;
    access_log off;
    expires 30d;
}

location / {
    try_files $uri $uri/ /index.php?$query_string;
    gzip_static on;
}
