location ~ /\.(env|git|svn|hg|htaccess|DS_Store) {
    deny all;
}

location ~* \.(composer\.(json|lock)|package\.json|yarn\.lock|sql|bak)$ {
    deny all;
}

location ~ ^/(vendor|node_modules|tests)/ {
    deny all;
}

location ~ \.\./ {
    deny all;
}

location ~* (phpunit|eval-stdin|thinkphp|pearcmd|docker) {
    deny all;
}
